<ul id="menu" class="page-sidebar-menu">
    <li {!! (Request::is('home') ? 'class="active"' : '') !!}>
        <a href="{{url('/home')}}">
            <i class="livicon" data-name="home" data-size="22" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Home</span>
        </a>
    </li>
    <li  {!! (Request::is('apply-leave') ? 'class="active"' : '') !!}>
        <a href="{{url('apply-leave')}}">
            <i class="livicon" data-name="folder-open" data-size="22" data-c="#F89A14" data-hc="#F89A14"
               data-loop="true"></i>
            <span class="title">Apply Leave</span>
        </a>
    </li>
    <li {!! (Request::is('my-application/accepted-application') || Request::is('my-application/rejected-application') || Request::is('my-application/pending-application')  ? 'class="active"' : '')  !!}>
        <a href="#">
            <i class="livicon" data-name="tasks" data-size="22" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">My Application</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('my-application/accepted-application') ? 'class="active"' : '') !!}>
                <a href="{{url('my-application/accepted-application')}}">
                    <i class="fa fa-angle-double-right"></i>
                    Accepted
                </a>
            </li>
            <li {!! (Request::is('my-application/rejected-application') ? 'class="active"' : '') !!}>
                <a href="{{url('my-application/rejected-application')}}">
                    <i class="fa fa-angle-double-right"></i>
                    Rejected
                </a>
            </li>
            <li {!! (Request::is('my-application/pending-application') ? 'class="active"' : '') !!}>
                <a href="{{url('my-application/pending-application')}}">
                    <i class="fa fa-angle-double-right"></i>
                    Pending
                </a>
            </li>

        </ul>

    </li>

    @if(Sentinel::inRole('admin') || Sentinel::inRole('authority'))
    <li {!! (Request::is('user-application') ? 'class="active"' : '') !!}>
        <a href="{{url('user-application')}}">
            <i class="livicon" data-name="inbox" data-size="22" data-c="#ef6f6c" data-hc="#ef6f6c"
               data-loop="true"></i>
            <span class="title">Requested App</span>

        </a>

    </li>
@endif


    <li {!! (Request::is('profile') ? 'class="active"' : '') !!}>
        <form action="{{url('profile')}}" method="get">
            <input name="prf" id="prf" type="hidden" value="{{Sentinel::getUser()->id}}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <a href="#" onclick="$(this).closest('form').submit()">
                <i class="livicon" data-name="facebook-alt" data-c="#418BCA" data-hc="#418BCA" data-size="22"
                   data-loop="true"></i>
                <span class="title">My Profile</span>
            </a>
        </form>


    </li>

    @if(Sentinel::inRole('admin') || Sentinel::inRole('authority'))

    <li {!! (Request::is('users') || Request::is('users-create')  ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="users" data-size="22" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">Users</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('users') ? 'class="active" ' : '') !!}>
                <a href="{{ url('users') }}">
                    <i class="fa fa-angle-double-right"></i>
                    User List
                </a>
            </li>
            <li {!! (Request::is('users-create') ? 'class="active"': '') !!}>
                <a href="{{ url('users-create') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Add New User
                </a>
            </li>
        </ul>
    </li>
@endif

    @if(Sentinel::inRole('admin')|| Sentinel::inRole('authority'))

        <li {!! (Request::is('settings')  ? 'class="active"' : '') !!}>
            <a href="{{url('settings')}}">
                <i class="livicon" data-name="settings" data-size="22" data-c="#F89A14" data-hc="#F89A14"
                   data-loop="true"></i>
                <span class="title">Setting</span>
            </a>
        </li>
@endif

    <!-- Menus generated by CRUD generator -->

</ul>

